// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZNVCYY-gIlm0BAa56C9k99v5RlZtl98k',
    appId: '1:536681005806:web:455979a8dd3e5d13b5a9ff',
    messagingSenderId: '536681005806',
    projectId: 'portfolio-5665b',
    authDomain: 'portfolio-5665b.firebaseapp.com',
    storageBucket: 'portfolio-5665b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_vknQXkviqvYS2AT2EkNWu4vbC30fOTs',
    appId: '1:536681005806:android:4741162e9bd33528b5a9ff',
    messagingSenderId: '536681005806',
    projectId: 'portfolio-5665b',
    storageBucket: 'portfolio-5665b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaMz_t0cEJSF1X-gSSJtoMZ0pR10H8nhQ',
    appId: '1:536681005806:ios:15b8f01d18719066b5a9ff',
    messagingSenderId: '536681005806',
    projectId: 'portfolio-5665b',
    storageBucket: 'portfolio-5665b.appspot.com',
    iosClientId:
        '536681005806-qksobuaf7vdo3162urc6omlp1mp9as6q.apps.googleusercontent.com',
    iosBundleId: 'com.orientedobject.devPortfolio',
  );
}
